### ISSUE TITLE
[suggestion] Increase wagon size available for loading cargo.

### ISSUE THREAD

**Issue by ghost** [muppet9010/Factorio-Single-Train-Unit#3]
2 tiles on each side is of the single train unit a quite small length available for cargo loading/unloading (and only 1/3 of its total length), while it's the most important part of stations designs (especially when optimizing for the loading speed).

Making the central cargo part of single train unit 4 tiles wide, and reducing the length of the locomotives to 1 tile each would make it easer to access the cargo and achieve a satisfying unloading speed,
This design still leaves enough space for loading fuel/unloading spent result from the locomotives through the use of two long inserters.

Feel free to discuss the suggestion or ask for more details.

**Comment by muppet9010** [comment]
If you can make it all be valid and inserters work at that length I'd very much welcome a PR.
I tried it initially back when making the mod and the various minimum sizes, gaps needed for cornering, etc made it impossible to have 4 middle inserters for cargo part.

**Comment by Ybaedbaenn** [comment]
I tried to set it up correctly, but it seems that the need to have the joints inside of vehicles' collision boxes combined with trains aligning to stops by the first of their joints make it impossible to contain each train part inside of their preferred tiles (locos in 1st and 6th, while the wagon is contained in 2nd to 5th with no overhang).

Since the game engine forces this kind of train to have tiles of their length on which there are two collision boxes (loco and wagon), inserters can be confused and put fuel in the wagon or cargo in the loco.

It can only be done if:
- the train is longer than a regular wagon,
- a script is used to park every train in a different way each time they use a stop,
- a script is used that sets inserters' targets correctly each time a train uses a stop.

Any of those seems like too complicated a solution for a problem that should have a simpler one. Since I'm new to Factorio modding, I'm not going to try to make any of those into a solution; that may not come out working (or may have some other unanticipated implications).

**Comment by Ybaedbaenn** [comment]
I tried to set it up correctly, but it seems that the need to have the joints inside of vehicles' collision boxes combined with trains aligning to stops by the first of their joints make it impossible to contain each train part inside of their preferred tiles (locos in 1st and 6th, while the wagon is contained in 2nd to 5th with no overhang).

Since the game engine forces this kind of train to have tiles of their length on which there are two collision boxes (loco and wagon), inserters can be confused and put fuel in the wagon or cargo in the loco.

It can only be done if:
- the train is longer than a regular wagon,
- a script is used to park every train in a different way each time they use a stop,
- a script is used that sets inserters' targets correctly each time a train uses a stop.

Any of those seems like too complicated a solution for a problem that should have a simpler one. Since I'm new to Factorio modding, I'm not going to try to make any of those into a solution; that may not come out working (or may have some other unanticipated implications).

**Comment by ghost** [comment]
I tried to set it up correctly, but it seems that the need to have the joints inside of vehicles' collision boxes combined with trains aligning to stops by the first of their joints make it impossible to contain each train part inside of their preferred tiles (locos in 1st and 6th, while the wagon is contained in 2nd to 5th with no overhang).

Since the game engine forces this kind of train to have tiles of their length on which there are two collision boxes (loco and wagon), inserters can be confused and put fuel in the wagon or cargo in the loco.

It can only be done if:
- the train is longer than a regular wagon,
- a script is used to park every train in a different way each time they use a stop,
- a script is used that sets inserters' targets correctly each time a train uses a stop.

Any of those seems like too complicated a solution for a problem that should have a simpler one. Since I'm new to Factorio modding, I'm not going to try to make any of those into a solution; that may not come out working (or may have some other unanticipated implications).
